apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-broker
  labels:
    app: broker
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mqtt
        image: {{ $.Values.mqtt_broker.image }}:{{ $.Values.mqtt_broker.imageTag }}
        ports:
        - containerPort: {{ $.Values.config.mqtt_broker.int.mqtt_port }}
          name: mqtt
        env:
        - name: http_proxy
          value: {{ $.Values.env.http_proxy }}
        - name: https_proxy
          value: {{ $.Values.env.https_proxy }}
        - name: no_proxy
          value: "{{ $.Values.env.no_proxy }},{{ $.Values.env.HOST_IP }}"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1883
          runAsGroup: 1883
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: mosquitto-config-volume
          mountPath: /mosquitto/config
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
      volumes:
      - name: mosquitto-config-volume
        configMap:
          name: broker
      - name: mosquitto-data
        emptyDir: {}
      - name: mosquitto-log
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: {{ $.Values.namespace }}
  labels:
    app: broker
spec:
  type: ClusterIP
  ports:
  - port: {{ $.Values.config.mqtt_broker.int.mqtt_port }}
    targetPort: {{ $.Values.config.mqtt_broker.int.mqtt_port }}
    name: mqtt
    protocol: TCP
  selector:
    app: broker
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: broker
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
